const quotes = [
    "A fit body, a calm mind, a house full of love. These things cannot be bought - they must be earned.",
    "The most important skill for getting rich is becoming a perpetual learner.",
    "You have to know for yourself what you're doing. It's not a spectator sport.",
    "The measure of wealth is freedom. The measure of health is lightness. The measure of intellect is judgment.",
    "The ability to be alone and happy is the foundation of all happiness.",
    "Desire is a contract you make with yourself to be unhappy until you get what you want.",
    "A rational person can find peace by cultivating indifference to things outside of their control.",
    "The secret to happiness is to be grateful for what you have and not to desire what you don't have.",
    "The more you know, the less you believe.",
    "If you're not willing to do a task for free, you're not going to be able to do it for a living.",
    "The reality is, life is a single-player game. You're born alone, you're going to die alone.",
    "You can't get rich renting out your time. You must own equity - a piece of a business - to gain your financial freedom.",
    "The most valuable things in life are the things that you can't buy.",
    "The meaning of life is to find your gift. The purpose of life is to give it away.",
    "A busy mind accelerates the passage of time. A calm mind slows down the passage of time.",
    "If you want to be successful, you have to be willing to do the things that others are not.",
    "You're not going to get rich renting out your time. You must own equity, a piece of a business, to gain your financial freedom.",
    "The best way to predict the future is to create it.",
    "The closer you are to the truth, the more silent you become.",
    "The older you get, the more you realize that the only thing that matters is your health.",
    "The best way to get what you want is to deserve what you want.",
    "The only way to do great work is to love what you do.",
    "The world is a reflection of your own mind.",
    "The only real prison is fear, and the only real freedom is freedom from fear.",
    "The best way to be happy is to make others happy.",
    "The key to happiness is to be grateful for what you have.",
    "The biggest mistake you can make is to believe that you have time.",
    "The only thing that is constant is change.",
    "The only thing that is real is the present moment.",
    "The only thing that matters is what you do now.",
    "The only true wisdom is in knowing you know nothing.",
    "The only way to get rid of a temptation is to yield to it.",
    "The only person you are destined to become is the person you decide to be.",
    "The only thing we have to fear is fear itself.",
    "The only way to find your passion is to try new things.",
    "The only way to make your dreams come true is to wake up.",
    "The only way to learn is to make mistakes.",
    "The only way to grow is to challenge yourself.",
    "The only way to be free is to let go.",
    "The only way to be happy is to be yourself.",
    "The only way to be successful is to be persistent.",
    "The only way to be rich is to be generous.",
    "The only way to be wise is to be humble.",
    "The only way to be strong is to be vulnerable.",
    "The only way to be beautiful is to be kind.",
    "The only way to be loved is to be lovable.",
    "The only way to be respected is to be respectable.",
    "The only way to be trusted is to be trustworthy.",
    "The only way to be a leader is to be a servant.",
    "The only way to be a friend is to be a friend.",
    "The only way to be a good parent is to be a good person.",
    "The only way to be a good student is to be a good teacher.",
    "The only way to be a good listener is to be a good speaker.",
    "The only way to be a good writer is to be a good reader.",
    "The only way to be a good artist is to be a good observer.",
    "The only way to be a good scientist is to be a good experimenter.",
    "The only way to be a good philosopher is to be a good thinker.",
    "The only way to be a good person is to be a good person.",
    "I don't have a mentor, but I have a lot of heroes.",
    "The best way to escape from a problem is to solve it.",
    "A good reputation is more valuable than money.",
    "The first step to getting what you want is to have the courage to get rid of what you don't.",
    "The more you praise and celebrate your life, the more there is in life to celebrate.",
    "The only way to have a friend is to be one.",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The best revenge is massive success.",
    "The only way to do great work is to love what you do.",
    "If you can dream it, you can achieve it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The only thing necessary for the triumph of evil is for good men to do nothing.",
    "The only thing worse than being blind is having sight but no vision.",
    "The only true failure is the failure to try.",
    "The only way to predict the future is to invent it.",
    "The only thing that will stop you from fulfilling your dreams is you.",
    "The only thing that can stop you is the belief that you can't.",
    "The only person you should try to be better than is the person you were yesterday.",
    "The only thing that holds you back is your own imagination.",
    "The only thing that we have to decide is what to do with the time that is given to us.",
    "The only thing that is impossible is the thing that you don't try.",
    "The only thing that is certain is uncertainty.",
    "The only thing that is eternal is the present moment.",
    "The only thing that is important is the love that you give.",
    "The only thing that is beautiful is the truth.",
    "The only thing that is powerful is the will.",
    "The only thing that is valuable is the knowledge.",
    "The only thing that is free is the mind.",
    "The only thing that is happy is the soul.",
    "The only thing that is peaceful is the heart.",
    "The only thing that is good is the virtue.",
    "The only thing that is bad is the vice.",
    "The only thing that is right is the justice.",
    "The only thing that is wrong is the injustice.",
    "The only thing that is wise is the reason.",
    "The only thing that is foolish is the passion.",
    "The only thing that is strong is the faith.",
    "The only thing that is weak is the doubt.",
]; 